### PR TITLE
I propose that repeated hits of the horn shouldn’t overlap.

### PR DESCRIPTION
**Pull request by itsmoops**
I feel as though it is a better user experience to be able to do multiple horn blasts in a row, to get that real rap horn feel.

### CODE REVIEW

**Comment by iammenasco** [comment]
This functionality already exists in `v0.0.2`.

I'd argue that the point of the rap-horn is to overlap, not play one after the other. Its to mimic (or mock) how ridiculous some music is that actually uses this sound when it does overlap.

**Comment by rodneykeeling** [comment]
> This functionality already exists in v0.0.2.

How do you enable it? I'm on v0.0.3, but I can't see any setting for it.

**Comment by iammenasco** [comment]
Run `apm install rap-horn@0.0.2` in your terminal on your user root, and you should be good to go :)

**Comment by iammenasco** [comment]
@itsmoops - You are right, this sounds loads better. Sorry for the long wait!

**Comment by iammenasco** [comment]
@itsmoops & @rodneykeeling - Released as `0.0.5`.

**Pull request merged**
